// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGskP8-6NrRvxZUJokuAAxi5GUPHBfWd0',
    appId: '1:990304440213:web:e00e5685a21040f272b09c',
    messagingSenderId: '990304440213',
    projectId: 'myhelp-oficial',
    authDomain: 'myhelp-oficial.firebaseapp.com',
    storageBucket: 'myhelp-oficial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoHVU_QZxSgbQ_A7mvEDGIts3jK0dCno',
    appId: '1:990304440213:android:1d67c42d59459c9d72b09c',
    messagingSenderId: '990304440213',
    projectId: 'myhelp-oficial',
    storageBucket: 'myhelp-oficial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZksi1VzAmUJJAAERALlW6KMcSed97eu4',
    appId: '1:990304440213:ios:733f9ca0f385b08772b09c',
    messagingSenderId: '990304440213',
    projectId: 'myhelp-oficial',
    storageBucket: 'myhelp-oficial.firebasestorage.app',
    iosBundleId: 'com.example.oficialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGskP8-6NrRvxZUJokuAAxi5GUPHBfWd0',
    appId: '1:990304440213:web:0b5b968437235d4472b09c',
    messagingSenderId: '990304440213',
    projectId: 'myhelp-oficial',
    authDomain: 'myhelp-oficial.firebaseapp.com',
    storageBucket: 'myhelp-oficial.firebasestorage.app',
  );
}